#!/user/bin/env zsh
# |== Directory Navigation Functions ==| #
#
# Description: Improved directory navigation using fzf

d () {
    # Test for directory path -> default to home
    dir_name=$(get-dir-h "$1")
    if [[ -z "${dir_name}" ]]; then
        echo -e "Specified Directory ${blue}${1}${reset} does not exist."
        echo "false"
        return 2
    fi
    dir_path=$(realpath "${dir_name}")

    choice="notempty"
    dir_traversal="false"

    # Run fzf to traverse directories
    while [[ -n "${choice}" ]]; do
        choice=$(fdfind . "$dir_path" -H --type d | sed "s|${dir_path}/||" | fzf --border-label=" 󰥨 ${dir_path}/ " --preview "eza --tree -l --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-time --no-permissions ${dir_path}/{}")

        if [[ -n "${choice}" ]]; then
            dir_traversal="true"

            cd "${dir_path}/${choice}" || return 2

            dir_path=$(realpath "${dir_path}/${choice}")
            dir_number=$(fdfind . "${dir_path}" --type d --max-depth 1 | wc -l)

            # stop loop if ther are no more directories to traverse
            if [[ "${dir_number}" -le 0 ]]; then
                choice=""
            fi
        fi
    done

    # Print data if neccessary
    if [[ "${dir_traversal}" == "true" ]]; then
        clear

        # Git repo?
        repo_path=$(git rev-parse --show-toplevel 2> /dev/null)

        # account for extra height of script output
        if [[ -n "${repo_path}" ]]; then
            repo-header

            header_size=$(repo-header | wc -l)
            extra_lines=$((header_size + 1))
        else
            extra_lines=1
        fi

            dir-overview . "${extra_lines}"
            echo
    fi
}
