#!/user/bin/env zsh
# |== Package Management Functions ==| #
#
# Description: Various functions that make dealing with packages and
# package managers easier. Various functions that improve the workflow
# for managing and investigating packages the various package managers.

# |= Installing Packages =>
ddf() {
	choice=$(apt-cache -n search '.*' | awk -F ' - ' '{print $1}' | fzf --height=100% --header-first --reverse --prompt='▶ ' --pointer='󱦰' --multi --preview-window="down" --preview 'apt show {}')

	if [ -n "$choice" ]; then
		echo "Installing ${choice}" | clr cyan
	    sudo nala install "${choice}"
	fi
}

# |= Man Pages =>

# Fzf Man Pages
fman() {
  manpage="echo {} | sed 's/\([[:alnum:][:punct:]]*\) (\([[:alnum:]]*\)).*/\2 \1/'"
  batman="${manpage} | xargs -r man | col -bx | batcat --language=man --plain --color always --theme=\"Nord\""
   man -k . | sort \
   | awk -v cyan=$(tput setaf 6) -v blue=$(tput setaf 4) -v res=$(tput sgr0) -v bld=$(tput bold) '{ $1=cyan bld $1; $2=res blue $2; } 1' \
   | fzf \
      -q "$1" \
      --ansi \
      --tiebreak=begin \
      --prompt=' Man > '  \
      --preview-window 'down' \
      --preview "${batman}" \
      --bind "enter:execute(${manpage} | xargs -r man)"
      # --bind "alt-c:+change-preview(cht.sh {1})+change-prompt(ﯽ Cheat > )" \
      # --bind "alt-m:+change-preview(${batman})+change-prompt( Man > )" \
      # --bind "alt-t:+change-preview(tldr --color=always {1})+change-prompt(ﳁ TLDR > )"
  # zle reset-prompt
}
