#!/user/bin/env zsh
# |== File Management Related Aliases ==| #
#
# Description: Aliases related to all facets of file management. Including navigation,
# editing, creation, deletion. etc.

# |= Fuzzy directory navigation
#
alias docs='d /home/rc/Documents' # document directories
alias blds='d /home/rc/Builds' # builds direcorties
alias r='d /home/rc/Repos'

alias .cfg='d /home/rc/.config' # .config directories
alias .lcl='d /home/rc/.local' # .local directories

# |= File management

alias fm="nvim -c Oil"

# |= File and directory command common flags

alias cpr="cp -r"
alias rmr="rm -r"
alias rmrf="rm -rf"
alias md="mkdir -p"

# |= Git management systems

alias lg="lazygit"

# |= Git statuses

alias gll="gita ll"
alias gls="gfold | grep -vi 'rilcritch'"
