#!/user/bin/env zsh
# |== List Aliases ==| #
#
# Description: Aliases for better listing

# |= EZA default

# alias eza="eza --color='always' --icons='always'"

# |= Basic listing
alias l='eza --group-directories-first --icons'
alias la='eza -a --group-directories-first --icons'

# |= Long listing
alias ls='eza -l --group-directories-first --no-permissions --no-filesize --icons --no-user --grid'
alias sl='eza -l --group-directories-first --no-permissions --no-filesize --icons --no-user --grid'
alias lsa='eza -la --group-directories-first --no-permissions --no-filesize --icons --no-user --grid'

alias ll='eza -l --group-directories-first --hyperlink'
alias lla='eza -la --group-directories-first --hyperlink'

# Directories only listing
alias ld='eza -D --icons'
alias lda='eza -Da --icons'

alias lf='eza -f --icons'
alias lfa='eza -fa --icons'
