#!/user/bin/env zsh
# |== List Aliases ==| #
#
# Description: Aliases for better listing

# |= EZA default

alias eza="eza --color='always' --icons='always'"

# |= Basic listing
alias ls='eza --group-directories-first --icons'
alias sl='eza --group-directories-first --icons'
alias lsa='eza -a --group-directories-first --icons'

# |= Long listing
alias ll='eza -l --group-directories-first --no-filesize --icons --no-user'
alias lll='eza -l --group-directories-first'

alias lla='eza -la --group-directories-first --no-filesize --icons --no-user'
alias llal='eza -la --group-directories-first'

# Directories only listing
alias ld='eza -D --icons'
alias lda='eza -Da --icons'

alias lf='eza -f --icons'
alias lfa='eza -fa --icons'
