#!/user/bin/env zsh
# |== Aliases Related to Searching ==| #
#
# Description: Aliases for searching functions, common search, and various ways to find thing
# on a pc

# |= fonts

alias fzfonts="fc-list | fzf"

# |= Command Info

# Which command
if test -n "$ZSH_VERSION"; then
    alias which="whence -v"
else
    alias which="which -a"
fi
