#!/usr/bin/env zsh
# |== ZSHRC OMZ Plugin Config Init ==|

# |- Directories

ZSH_PATH="${HOME}/Repos/zsh-ril"
P_CONFS="${ZSH_PATH}/omz/plugin-confs"

# |- Plugin Config Imports

# vim:fileencoding=utf-8:foldmethod=marker
